name=GhidraMCP
description=A plugin that runs an embedded HTTP server to expose program data. Provides 176 endpoints for reverse engineering automation. Plugin version ${project.version}.
author=Ben Ethington
createdOn=2025-03-22
version=${ghidra.version}
